### ISSUE TITLE
fedora30  No suitable version of LLVM was found system-wide or pointed

### ISSUE THREAD

**Issue by ghost** [maekawatoshiki/ferrugo#1]
error: failed to run custom build command for `llvm-sys v60.4.1 (registry `https://mirrors.ustc.edu.cn/crates.io-index/`)`

Caused by:
  process didn't exit successfully: `/tmp/ferrugo/target/debug/build/llvm-sys-3024158b1ce43268/build-script-build` (exit code: 101)
--- stdout
Didn't find usable system-wide LLVM.
No suitable version of LLVM was found system-wide or pointed
                  to by LLVM_SYS_60_PREFIX.

                  Consider using `llvmenv` to compile an appropriate copy of LLVM, and
                  refer to the llvm-sys documentation for more information.

                  llvm-sys: https://crates.io/crates/llvm-sys
                  llvmenv: https://crates.io/crates/llvmenv

--- stderr
thread 'main' panicked at 'Could not find a compatible version of LLVM', 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by livingkang** [comment]
dnf install llvm6
